backend:
  name: git-gateway
  branch: master # Branch to update
media_folder: 'dist/_uploads/images' #Live image Uploads
public_folder: '/uploads/images' #prebuild image Uploads
collections:
  - name: 'posts' #Name of tcollection to match posts.json file's tag
    label: 'Posts' #CMS collection name
    folder: 'posts' #Folder where posts are
    create: true #Can a new posts be created
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' #this sets the URL for the post
    fields: #What fields are displayed to edit the post
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'layouts/post.njk',
        } #Layout option
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date', default: '' }
      - { label: 'Post Body', name: 'body', widget: 'markdown' }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
