backend:
  name: git-gateway
  branch: master # Branch to update
media_folder: 'dist/uploads/images' #Live image Uploads
public_folder: '/uploads/images' #prebuild image Uploads
collections:
  - name: 'post' #Collection name that matches the .json tags
    label: 'Posts' #CMS collection name
    folder: 'src/posts' #Folder where posts live
    create: true #Can a new posts be created
    slug: '{{pageTitle}}' #this sets the URL for the post
    fields: #What fields are displayed to edit the post
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'pages/post.njk',
        } #Layout option
      - { label: 'Title', name: 'pageTitle', widget: 'string' }
      - { label: 'Description', name: 'pageDescription', widget: 'string' }
      - { label: 'Hero Image', name: 'heroImage', widget: 'image' }
      - { label: 'Date', name: 'date', widget: 'date', default: '' }
      - { label: 'Post Body', name: 'body', widget: 'markdown' }
